version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-net
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: node
    container_name: node-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s node index.js
    networks:
      - node-net
    tty: true
    volumes:
      - /app/node_modules
      - ./node:/app
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-net

volumes:
  mysql-data:

networks:
  node-net:
    driver: bridge